name: misskey_dog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.8
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true
