name: misskey_dog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  characters: ^1.3.0
  collection: ^1.18.0
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  i18n_extension: ^10.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3
  riverpod_annotation: ^2.3.2
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.8
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.6
  retrofit_generator: ^8.0.4
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
